title: highfence devlog
description: 게임, 개발 그리고 AI 이야기. 생각나는대로 최대한 잡다한 글을 씁시다.
url: "https://highfence.github.io"
baseurl: ""
lang: ko-KR
timezone: Asia/Seoul

permalink: /posts/:slug/
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - node_modules
  - public
  - vendor
  - Gemfile.lock
  - README.md
  - LICENSE.txt
